In [1]:
from NeuralNetwork import Neural_Network
import numpy as np
import jax.numpy as jnp

## Initiate neural network

1. Set up the design matrix with the inputs as discussed above and a vector containing the output, the so-called targets. Note that the design matrix is the same for all gates. You need just to define different outputs.

In [24]:
np.random.seed(1234)

# Create design matrix
X = jnp.array([[0, 0],
               [0, 1],
               [1, 0],
               [1, 1]])

X = jnp.array([[0, 1]])

# The XOR gate
target_XOR = jnp.array( [ 0, 1 ,1, 0])
# The OR gate
target_OR = jnp.array( [ 0, 1 ,1, 1])
# The AND gate
target_AND = jnp.array( [ 0, 0 ,0, 1])

target = jnp.array([0])

2. Construct a neural network with only one hidden layer and two hidden nodes using the Sigmoid function as activation function.

In [25]:
n_hidden_layers = 1
n_hidden_nodes = 2
n_outputs = 1
learning_rate=0.1

ffnn = Neural_Network(X, target, n_hidden_layers, n_hidden_nodes, n_outputs, 
                      learning_rate, activation_function='sigmoid',
                      classification_problem=True)

str(ffnn)

'Neural Network with 1 hidden layers and [2] nodes per layer. The activation function is sigmoid.'

3. Set up the output layer with only one output node and use again the Sigmoid function as activation function for the output.

In [26]:
print(f'Output layer has {ffnn.output_layer.n_nodes} node and uses the {str(ffnn.output_layer.activation_function)} as activation function')

Output layer has 1 node and uses the sigmoid as activation function


4. Initialize the weights and biases and perform a feed forward pass and compare the outputs with the targets.

In [27]:
print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')

Weights hidden layer 1:
[[ 0.04714352 -0.11909757]
 [ 0.1432707  -0.03126519]]
Biases hidden layer 1:
[[0.01 0.01]]
weights output layer:
[[-0.07205887]
 [ 0.08871629]]
Biases output layer:
[[0.01]]


In [28]:
ffnn.feed_forward()

print("Final prediction before training:\n"
      f"{ffnn.output_layer.output}")

Final prediction before training:
[[1.]]


5. Set up the cost function (cross entropy for classification of binary cases).

6. Calculate the gradients needed for the back propagation part.

7. Use the gradients to train the network in the back propagation part. Think of using automatic differentiation.

In [29]:
ffnn.feed_backward()

print('Weights and biases after one backward propagation: \n')

print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')


Weights and biases after one backward propagation: 

Weights hidden layer 1:
[[ 4.71435164e-02 -1.19097569e-01]
 [ 8.35989224e+13  7.72768179e+13]]
Biases hidden layer 1:
[[8.35989224e+13 7.72768179e+13]]
weights output layer:
[[-13455304.07205887]
 [-12366392.71128371]]
Biases output layer:
[[-24998576.]]


8. Train the network and study your results and compare with results obtained either with scikit-learn or TensorFlow.

In [30]:
ffnn.train()

print('Weights and biases after training: \n')

print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')

print("\nFinal prediction after training:\n"
      f"{ffnn.output_layer.output}")


C:\Users\vildesn\FYS_STK_4155\Projects\Project 2\activation_functions.py:33: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


Weights and biases after training: 

Weights hidden layer 1:
[[ 4.71435164e-02 -1.19097569e-01]
 [ 8.35989224e+13  7.72768179e+13]]
Biases hidden layer 1:
[[8.35989224e+13 7.72768179e+13]]
weights output layer:
[[-13455304.07205887]
 [-12366392.71128371]]
Biases output layer:
[[-24998576.]]

Final prediction after training:
[[0.]]
