In [1]:
from GD_class import GradientDescent
import autograd.numpy as np

In [2]:
def make_design_matrix(x, degree):
    "Creates the design matrix for the given polynomial degree and input data"
    
    X = np.zeros((len(x), degree+1))
    
    for i in range(X.shape[1]):
        X[:,i] = np.power(x, i)
        
    return X

def cost_function_OLS(X, y, beta):
    return (1.0/n)*np.sum((y-X.dot(beta))**2)

def analytical_gradient(X, y, beta):
    return (2.0/n)*np.dot(X.T, ((np.dot(X,beta))-y))
    

true_beta = [2, 0.5, 3.2]

n = 100

x = np.linspace(0, 1, n)
y = np.sum(np.asarray([x ** p * b for p, b in enumerate(true_beta)]),
                axis=0) + 0.1 * np.random.normal(size=len(x))

# Making a design matrix to use for linear regression part
degree = 2
X = make_design_matrix(x, degree)

In [9]:
learning_rate = 0.1
tol=1e-3
beta_guess = np.random.rand(3)


In [29]:
grad_descent = GradientDescent(X, y, learning_rate, tol, cost_function_OLS)
grad_descent.cost_gradient(X, y, beta_guess)

array([-5.35380067, -3.19965551, -2.34540333])

In [32]:
grad_descent = GradientDescent(X, y, learning_rate, tol, cost_function_OLS, analytic_gradient=analytical_gradient)
grad_descent.cost_gradient(X, y, beta_guess)

array([-5.35380067, -3.19965551, -2.34540333])

In [10]:
grad_descent = GradientDescent(X, y, learning_rate, tol, cost_function_OLS, analytic_gradient=analytical_gradient)
max_iter = 100000
beta_calculated = grad_descent.iterate(0.1, max_iter)

Converged after 3719 iterations


In [11]:
print(beta_calculated)

[1.94935367 0.70470506 3.03308441]
