In [1]:
from NeuralNetwork import Neural_Network
import numpy as np
import jax.numpy as jnp

## Initiate neural network

1. Set up the design matrix with the inputs as discussed above and a vector containing the output, the so-called targets. Note that the design matrix is the same for all gates. You need just to define different outputs.

In [2]:
np.random.seed(1234)

# Create design matrix
X = jnp.array([[0, 0],
               [0, 1],
               [1, 0],
               [1, 1]])
# Since X is our input we need it to be a vector, hence we reshape it 
#X = X.reshape((X.shape[0]*X.shape[1], 1))

# The XOR gate
target_XOR = jnp.array( [ 0, 1 ,1, 0])
# The OR gate
target_OR = jnp.array( [ 0, 1 ,1, 1])
# The AND gate
target_AND = jnp.array( [ 0, 0 ,0, 1])



2. Construct a neural network with only one hidden layer and two hidden nodes using the Sigmoid function as activation function.

In [3]:
n_hidden_layers = 1
n_hidden_nodes = 2
n_outputs = 1

ffnn = Neural_Network(X, target_OR, n_hidden_layers, n_hidden_nodes, n_outputs, activation_function='sigmoid')
str(ffnn)

'Neural Network with 1 hidden layers and [2] nodes per layer. The activation function is sigmoid.'

3. Set up the output layer with only one output node and use again the Sigmoid function as activation function for the output.

In [4]:
print(f'Output layer has {ffnn.output_layer.n_nodes} node and uses the {str(ffnn.output_layer.activation_function)} as activation function')

Output layer has 1 node and uses the sigmoid as activation function


4. Initialize the weights and biases and perform a feed forward pass and compare the outputs with the targets.

In [5]:
print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')

Weights hidden layer 1:
[[ 0.04714352 -0.11909757]
 [ 0.1432707  -0.03126519]]
Biases hidden layer 1:
[[0.01 0.01]]
weights output layer:
[[-0.07205887]
 [ 0.08871629]]
Biases output layer:
[[0.01]]


In [6]:
ffnn.feed_forward()
print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')

TypeError: dot_general requires contracting dimensions to have the same shape, got (4,) and (2,).