# Neural Network with PyTorch framework

# Import libraries

In [1]:
import numpy as np
import torch

from torch import nn, optim
from tqdm import tqdm
from Neural_Network_with_PyTorch import Neural_Network_PyTorch
from sklearn.metrics import accuracy_score

## Create Neural network and perform passes

1. Set up the design matrix with the inputs as discussed above and a vector containing the output, the so-called targets. Note that the design matrix is the same for all gates. You need just to define different outputs.

We start by defining a helper function that allows us to convert a numpy array to a PyTorch tensor, with or without the gradient flag.  

In [2]:
# Create design matrix
X = torch.Tensor([[0, 0], [0, 1], [1, 0], [1, 1]]).requires_grad_(True)

# The XOR gate
target_XOR = torch.Tensor([ 0, 1 ,1, 0]).view(-1, 1)
# The OR gate
target_OR = torch.Tensor([ 0, 1 ,1, 1]).view(-1, 1)
# The AND gate
target_AND = torch.Tensor([ 0, 0 ,0, 1]).view(-1, 1)

2. Construct a neural network with only one hidden layer and two hidden nodes using the Sigmoid function as activation function.
3. Set up the output layer with only one output node and use again the Sigmoid function as activation function for the output.

In [3]:
# Network design
n_inputs = X.shape[1]
n_hidden_layers = 1
n_hidden_nodes = 2
n_outputs = 1

# Create network
ffnn = Neural_Network_PyTorch(n_inputs, 
                              n_hidden_layers, n_hidden_nodes, 
                              n_outputs, 
                              activation_function_hidden_layers='sigmoid',
                              activation_function_output_layer='sigmoid')

print('Model parameters')
print(list(ffnn.parameters()))

Sigmoid()
Model parameters
[Parameter containing:
tensor([[ 0.6733,  0.4288],
        [ 0.5845, -0.1015]], requires_grad=True), Parameter containing:
tensor([-0.4355,  0.4374], requires_grad=True), Parameter containing:
tensor([[-0.2478,  0.1221]], requires_grad=True), Parameter containing:
tensor([0.5650], requires_grad=True)]


5. Set up the cost function (cross entropy for classification of binary cases).

The evaluation criterion in this case is the cross entropy function. Therefor we create a cost function object from the cost_function_PyTorch class.

In [4]:
critertion = nn.MSELoss()
str(critertion)

'MSELoss()'

Now we calculate the cost function for the output of the network.

6. Calculate the gradients needed for the back propagation part.

In order to perform the back propagation part, we need to calculate the gradients of the cost function with respect to the weights and biases. This is done by the autograd package of PyTorch. We therefor initiate an optimizer object from the Gradient_Descent_PyTorch class based on the designed neural network.

In [5]:
learning_rate = 0.01

optimizer = optim.Adam(ffnn.parameters(), learning_rate)
print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)


4. Perform the feed-forward pass and calculate the output of the network.

7. Use the gradients to train the network in the back propagation part. Think of using automatic differentiation.

In [8]:
input = X
all_losses = []
current_loss = 0
plot_every = 100
for epoch in range(1000):
    ffnn.train()
    # Zero the gradients
    optimizer.zero_grad()    

    # Forward pass to get output/logits
    target_pred = ffnn.feed_forward(input)
    
    # Calculate loss and do backpropagation
    loss = critertion(target_pred, target_XOR)
    loss.backward()
    
    # Updating neural network parameters: w = w - learning_rate * gradient
    optimizer.step()    
    current_loss += loss
    
    
    if epoch % plot_every == 0:
        acc = accuracy_score(ffnn.classify(target_pred), target_XOR.detach().numpy())
        all_losses.append(current_loss / plot_every)
        
        print(f'Epoch: {epoch}:\n Loss: {current_loss / plot_every} \n accuracy: {acc}')
        current_loss = 0

print(ffnn.classify(target_pred))

Epoch: 0:
 Loss: 2.210644743172452e-05 
 accuracy: 1.0
Epoch: 100:
 Loss: 0.0020973042119294405 
 accuracy: 1.0
Epoch: 200:
 Loss: 0.0018934904364868999 
 accuracy: 1.0
Epoch: 300:
 Loss: 0.0017163539305329323 
 accuracy: 1.0
Epoch: 400:
 Loss: 0.0015613837167620659 
 accuracy: 1.0
Epoch: 500:
 Loss: 0.0014250017702579498 
 accuracy: 1.0
Epoch: 600:
 Loss: 0.0013043283252045512 
 accuracy: 1.0
Epoch: 700:
 Loss: 0.001197035307995975 
 accuracy: 1.0
Epoch: 800:
 Loss: 0.0011012147879227996 
 accuracy: 1.0
Epoch: 900:
 Loss: 0.0010152923641726375 
 accuracy: 1.0
[0, 1, 1, 0]
