In [13]:
from NeuralNetwork import Neural_Network
import numpy as np
import jax.numpy as jnp

## Initiate neural network

1. Set up the design matrix with the inputs as discussed above and a vector containing the output, the so-called targets. Note that the design matrix is the same for all gates. You need just to define different outputs.

In [14]:
np.random.seed(1234)

# Create design matrix
X = jnp.array([[0, 0],
               [0, 1],
               [1, 0],
               [1, 1]])

X = jnp.array([[0, 1]])

# The XOR gate
target_XOR = jnp.array( [ 0, 1 ,1, 0])
# The OR gate
target_OR = jnp.array( [ 0, 1 ,1, 1])
# The AND gate
target_AND = jnp.array( [ 0, 0 ,0, 1])

target = jnp.array([0])

NameError: name 'np' is not defined

2. Construct a neural network with only one hidden layer and two hidden nodes using the Sigmoid function as activation function.

In [15]:
n_hidden_layers = 1
n_hidden_nodes = 2
n_outputs = 1
learning_rate=0.1

ffnn = Neural_Network(X, target, n_hidden_layers, n_hidden_nodes, n_outputs, 
                      learning_rate, activation_function='sigmoid',
                      classification_problem=True)

str(ffnn)

'Neural Network with 1 hidden layers and [2] nodes per layer. The activation function is sigmoid.'

3. Set up the output layer with only one output node and use again the Sigmoid function as activation function for the output.

In [16]:
print(f'Output layer has {ffnn.output_layer.n_nodes} node and uses the {str(ffnn.output_layer.activation_function)} as activation function')

4. Initialize the weights and biases and perform a feed forward pass and compare the outputs with the targets.

In [17]:
print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')

In [18]:
ffnn.feed_forward()

print("Final prediction before training:\n"
      f"{ffnn.output_layer.output}")

Final prediction before training:
[[1.]]


5. Set up the cost function (cross entropy for classification of binary cases).

6. Calculate the gradients needed for the back propagation part.

7. Use the gradients to train the network in the back propagation part. Think of using automatic differentiation.

In [19]:
ffnn.feed_backward()

print('Weights and biases after one backward propagation: \n')

print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')


Weights and biases after one backward propagation: 

Weights hidden layer 1:
[[ 4.71435164e-02 -1.19097569e-01]
 [ 8.35989224e+13  7.72768179e+13]]
Biases hidden layer 1:
[[8.35989224e+13 7.72768179e+13]]
weights output layer:
[[-13455304.07205887]
 [-12366392.71128371]]
Biases output layer:
[[-24998576.]]


8. Train the network and study your results and compare with results obtained either with scikit-learn or TensorFlow.

In [20]:
ffnn.train()

print('Weights and biases after training: \n')

print('Weights hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].weights}')
print('Biases hidden layer 1:\n'
      f'{ffnn.hidden_layers[0].biases}')

print('weights output layer:\n'
      f'{ffnn.output_layer.weights}')
print('Biases output layer:\n'
      f'{ffnn.output_layer.biases}')

print("\nFinal prediction after training:\n"
      f"{ffnn.output_layer.output}")


Weights and biases after training: 

Weights hidden layer 1:
[[ 4.71435164e-02 -1.19097569e-01]
 [ 8.35989224e+13  7.72768179e+13]]
Biases hidden layer 1:
[[8.35989224e+13 7.72768179e+13]]
weights output layer:
[[-13455304.07205887]
 [-12366392.71128371]]
Biases output layer:
[[-24998576.]]

Final prediction after training:
[[0.]]


In [27]:
np.random.seed(1234)

# Create design matrix
X_orig = jnp.array([[0, 0],
               [0, 1],
               [1, 0],
               [1, 1]])

#X = jnp.array([[0, 1]])

# The XOR gate
target_XOR = jnp.array( [ 0, 1 ,1, 0])
# The OR gate
target_OR = jnp.array( [ 0, 1 ,1, 1])
# The AND gate
target_AND = jnp.array( [ 0, 0 ,0, 1])

#target = jnp.array([0])


n_hidden_layers = 1
n_hidden_nodes = 2
n_outputs = 1
learning_rate=0.1

In [28]:
#Testing AND gate
NN_output_AND = []

# AND gate
for X_row, target_row in zip(X_orig, target_AND):

    X = jnp.array([X_row])
    target = jnp.array([target_row])

    ffnn = Neural_Network(X, target, n_hidden_layers, n_hidden_nodes, n_outputs,
                      learning_rate, activation_function='sigmoid',
                      classification_problem=True)

    ffnn.feed_forward()

    ffnn.feed_backward()
    ffnn.train()

    NN_output_AND.append(ffnn.output_layer.output)

print(NN_output_AND)


[Array([[0.]], dtype=float32, weak_type=True), Array([[0.]], dtype=float32, weak_type=True), Array([[0.]], dtype=float32, weak_type=True), Array([[1.]], dtype=float32, weak_type=True)]


In [29]:

#Testing OR gate

NN_output_OR = []

# or gate
for X_row, target_row in zip(X_orig, target_OR):

    X = jnp.array([X_row])
    target = jnp.array([target_row])

    ffnn = Neural_Network(X, target, n_hidden_layers, n_hidden_nodes, n_outputs,
                      learning_rate, activation_function='sigmoid',
                      classification_problem=True)

    ffnn.feed_forward()

    ffnn.feed_backward()
    ffnn.train()

    NN_output_OR.append(ffnn.output_layer.output)

print(NN_output_OR)


[Array([[0.]], dtype=float32, weak_type=True), Array([[1.]], dtype=float32, weak_type=True), Array([[1.]], dtype=float32, weak_type=True), Array([[1.]], dtype=float32, weak_type=True)]


In [30]:
#Testing xor gate

NN_output_XOR = []

# xor gate
for X_row, target_row in zip(X_orig, target_XOR):

    X = jnp.array([X_row])
    target = jnp.array([target_row])

    ffnn = Neural_Network(X, target, n_hidden_layers, n_hidden_nodes, n_outputs,
                      learning_rate, activation_function='sigmoid',
                      classification_problem=True)

    ffnn.feed_forward()

    ffnn.feed_backward()
    ffnn.train()

    NN_output_XOR.append(ffnn.output_layer.output)

print(NN_output_XOR)


[Array([[0.]], dtype=float32, weak_type=True), Array([[1.]], dtype=float32, weak_type=True), Array([[1.]], dtype=float32, weak_type=True), Array([[0.]], dtype=float32, weak_type=True)]


In [31]:
def accuracy_test(y_true, y_pred):
    # y_true is the true labels of the data
    # y_pred is the predicted labels of the data by the neural network
    # Both y_true and y_pred are numpy arrays of the same shape

    # Compare y_true and y_pred element-wise and count the number of matches
    matches = 0
    for true, pred in zip(y_true, y_pred):
        if true == pred:
            matches = matches + 1

    # Calculate the accuracy as the ratio of matches to the total number of data points
    accuracy = matches / len(y_true)

    # Return the accuracy as a percentage
    return accuracy * 100


In [32]:

accuracy_AND_gate = accuracy_test(target_AND, NN_output_AND)
accuracy_OR_gate = accuracy_test(target_OR, NN_output_OR)
accuracy_XOR_gate = accuracy_test(target_XOR, NN_output_XOR)

print(accuracy_AND_gate)
print(accuracy_OR_gate)
print(accuracy_XOR_gate)

100.0
100.0
100.0
